Gemfile, Gemfile.lock, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, app/views/shared/_flashes.html.erb, app/views/shared/_navbar.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20230529130445_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
j'ai fait le devise mais pas encore de style !
=> devise done

db/migrate/20230529140855_add_attributes_to_user.rb, db/schema.rb
=> attributes added to users

app/models/booking.rb, app/models/flat.rb, app/models/user.rb, db/migrate/20230529144509_create_flats.rb, db/migrate/20230529144836_create_bookings.rb, db/schema.rb, test/models/booking_test.rb, test/models/flat_test.rb
=> models created

Gemfile.lock, app/controllers/flats_controller.rb, app/views/flats/edit.html.erb, app/views/flats/index.html.erb, app/views/flats/new.html.erb, app/views/flats/show.html.erb, config/routes.rb, test/controllers/flats_controller_test.rb
=> flat controller created

app/controllers/bookings_controller.rb, app/views/bookings/show.html.erb, config/routes.rb, test/controllers/bookings_controller_test.rb
=> -mbookings controller created

app/controllers/pages_controller.rb, config/routes.rb
=> Routes done

app/controllers/flats_controller.rb, app/views/bookings/show.html.erb, app/views/flats/show.html.erb
pouvons nous valider la show du flat avec l'action ?
=> show flat done and action

app/views/flats/_form.html.erb
=> adding partial form for booking a flat

db/migrate/20230529144509_create_flats.rb, db/schema.rb, db/seeds.rb
=> seeds done

db/migrate/20230529144509_create_flats.rb, db/schema.rb, db/seeds.rb
=> added image_url to tables and seed

app/controllers/bookings_controller.rb, app/views/flats/show.html.erb
=> actions done

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/bookings/show.html.erb, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb
=> ajout du footer

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_navbar.scss, app/views/flats/index.html.erb
=> cards updated

app/assets/stylesheets/components/_bookingscard.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_home.scss, app/views/dashboards/index.html.erb
=> added container and changed color

app/assets/stylesheets/components/_alert.scss, app/assets/stylesheets/components/_bookingscard.scss, app/views/dashboards/index.html.erb, app/views/devise/sessions/new.html.erb
=> index dashboard updated

app/assets/stylesheets/components/_card_show_flat.scss, app/assets/stylesheets/components/_form_airbnb.scss, app/assets/stylesheets/components/_index.scss, app/javascript/controllers/datepicker_controller.js, app/views/flats/_form.html.erb, app/views/flats/show.html.erb, app/views/layouts/application.html.erb, config/importmap.rb
=> show terminé

app/assets/stylesheets/components/_avatar.scss, app/views/shared/_navbar.html.erb
=> avatar and text align of navbar

Gemfile, app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb, db/schema.rb
=> navbar carré

app/assets/stylesheets/components/_form_create_flat.scss, app/views/flats/new.html.erb
=> modifs de la view de create flat

app/assets/stylesheets/components/_boutons.scss, app/views/dashboards/index.html.erb, app/views/pages/myhouses.html.erb
=> Front changes
